# Generated by Django 3.2.25 on 2024-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
