# Generated by Django 3.2.25 on 2024-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_momento_venta',
            field=models.FloatField(default=0),
        ),
    ]
